<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
    <ApplicationIcon>..\assets\AppIcon.ico</ApplicationIcon>
  </PropertyGroup>
  <ItemGroup>
    <AvaloniaResource Include="..\assets\Icon.png" LogicalName="Icon.png" />
    <AvaloniaResource Include="..\assets\AppIcon.png" LogicalName="AppIcon.png" />
    <PackageReference Include="Avalonia" Version="11.3.2" />
    <PackageReference Include="Avalonia.Desktop" Version="11.3.2" />
    <PackageReference Include="Avalonia.Themes.Fluent" Version="11.3.2" />
    <PackageReference Include="System.IO.Ports" Version="9.0.7" />
    <PackageReference Include="System.Management" Version="9.0.7" />
  </ItemGroup>
</Project>
